# 🧠 Introducción a NumPy

**Duración:** 4 horas  
**Objetivo:** Aprender los fundamentos de NumPy para el manejo eficiente de datos numéricos en Python: arrays, operaciones vectorizadas, indexación y slicing.

---

## 📌 Contenido:
1. ¿Por qué NumPy? Motivación y comparación con listas  
2. Creación de arrays: cómo generar estructuras para trabajar datos  
3. Indexación y slicing: cómo acceder y manipular datos  
4. Operaciones vectorizadas: cómo aprovechar la eficiencia de NumPy  
5. Funciones útiles para análisis y transformación  
6. Ejercicio práctico final

---

## 1️⃣ ¿Por qué NumPy?

Python es excelente para programar, pero sus listas no están optimizadas para cálculos numéricos masivos. NumPy resuelve esto ofreciendo arrays que son:
- Más rápidos
- Más compactos
- Con operaciones matemáticas integradas
- Compatibles con bibliotecas como pandas, matplotlib, scikit-learn, etc.

### 🧪 Comparativa de rendimiento

```python
import numpy as np

lista = list(range(1000000))
array = np.arange(1000000)

%timeit [x**2 for x in lista]
%timeit array**2


In [4]:
import numpy as np

lista = list(range(1000000))         # Lista de Python con 1 millón de elementos
array = np.arange(1000000)           # Arreglo de NumPy con 1 millón de elementos

%timeit [x**2 for x in lista]        # Tiempo que toma elevar al cuadrado usando lista
                    # Tiempo que toma elevar al cuadrado usando NumPy


66.2 ms ± 3.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
%timeit array**2 

1.4 ms ± 452 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 💡 ¿Qué significa?
List Comprehension (lista): tarda ~81.5 ms en completar la operación.

NumPy array: tarda ~1.11 ms, mucho más rápido.

🚀 Conclusión:
NumPy es muchísimo más rápido para operaciones numéricas vectorizadas como esta.

Esto se debe a que NumPy está implementado en C y realiza operaciones a nivel de bloque (sin bucles de Python).

## 2️⃣ Crear arrays: el punto de partida para trabajar con datos
Antes de procesar datos, necesitas representarlos. En NumPy usamos arrays: estructuras similares a listas, pero más potentes.

In [6]:
a = np.array([1, 2, 3])
print("Array desde lista:", a)


Array desde lista: [1 2 3]


### 🔧 Crear arrays vacíos o con valores iniciales
Estas funciones son útiles cuando quieres inicializar estructuras antes de llenarlas con datos:

In [7]:
np.zeros((2, 3))     # Útil para inicializar una matriz donde se cargarán valores
np.ones(5)           # Útil como multiplicador o marcador
np.full((2, 2), 7)   # Inicializar con un valor específico
np.eye(3)            # Matriz identidad (muy usada en álgebra lineal)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 🔢 Generar rangos o secuencias de valores
Cuando queremos crear secuencias sin escribirlas manualmente:

In [9]:
np.arange(0, 10, 2)      # Como range(), pero en array

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 1, 4)     # Divide de forma equidistante (para gráficos, por ejemplo)

array([0.        , 0.33333333, 0.66666667, 1.        ])

## 🔍 Propiedades básicas de los arrays

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)     # Tamaño de cada dimensión
print(a.ndim)      # Número de dimensiones
print(a.size)     # Total de elementos
print(a.dtype)     # Tipo de dato (int, float, etc.)

(2, 3)
2
6
int32


## 🧪 Ejercicio 1: Creación de arrays
1. Crea un array del 0 al 9

2. Crea una matriz 3x3 de ceros

3. Crea una secuencia de 5 valores entre 0 y 1

4. ¿Qué utilidad tendría un array lleno de -1?

## 3️⃣ Indexación y slicing: acceder a tus datos
Una vez tienes datos, necesitas consultarlos, cortarlos, combinarlos...
### 🔍 Acceder a elementos individuales

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[0, 1]  # Segundo elemento de la primera fila


2

### ✂️ Slicing (corte de arrays)
Es como cortar un archivo CSV: elegir filas, columnas, regiones.

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print(a[0:, 1:])    # Submatriz desde [1,1] hasta el final
print(a[:, 0])      # Primera columna

[[2 3]
 [5 6]]
[1 4]


### 🧠 Indexación booleana: filtrar según condiciones
Ideal para análisis de datos, por ejemplo, seleccionar notas > 7.

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]   # Devuelve [4, 5, 6]


array([4, 5, 6])

### 🎯 Fancy indexing: acceder a múltiples índices

In [ ]:
a = np.array([10, 20, 30, 40, 50])
a[[0, 2, 4]]     # Devuelve [10, 30, 50]


array([10, 30, 50])

In [ ]:
a = np.array([[10, 20, 30, 40, 50]])
a[0][[0, 2, 4]]

In [43]:
a[0::2]

array([10, 30, 50])

 ### Ejercicio 2: Indexación
Crea una matriz 5x5 con valores del 1 al 25

Extrae la diagonal principal

Extrae las esquinas

Filtra los valores mayores a 10

In [2]:
import numpy as np

# Crear la matriz 5x5 con valores del 1 al 25
matriz = np.arange(1, 26).reshape(5, 5)
print("Matriz 5x5:")
print(matriz)

# Extraer la diagonal principal
diagonal = np.diag(matriz)
print("\nDiagonal principal:")
print(diagonal)

# Extraer las esquinas
esquinas = np.array([matriz[0, 0], matriz[0, -1], matriz[-1, 0], matriz[-1, -1]])
print("\nEsquinas:")
print(esquinas)

# Filtrar los valores mayores a 10
mayores_que_10 = matriz[matriz > 10]
print("\nValores mayores a 10:")
print(mayores_que_10)


Matriz 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Diagonal principal:
[ 1  7 13 19 25]

Esquinas:
[ 1  5 21 25]

Valores mayores a 10:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


## 4️⃣ Operaciones vectorizadas: cálculo eficiente
Las operaciones vectorizadas son el corazón de NumPy: permiten escribir código más limpio y mucho más rápido.

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)       # Suma elemento a elemento
print(a * b)       # Producto elemento a elemento
print(a ** 2)      # Potencia


[5 7 9]
[ 4 10 18]
[1 4 9]


In [57]:
#Comparaciones
a > 2
a < b

array([ True,  True,  True])

In [58]:
a

array([1, 2, 3])