# Introducción a NumPy

## ¿Qué es NumPy?

NumPy (Numerical Python) es una librería fundamental para la computación científica con Python. Nos permite trabajar de manera eficiente con **arreglos** (arrays) y **matrices** (arrays multidimensionales) que ofrecen gran rapidez y flexibilidad en el manejo de datos numéricos.

## ¿Por qué es útil?

- **Arreglos eficientes**: NumPy está optimizado para realizar operaciones sobre arreglos de gran tamaño de forma muy rápida.
- **Herramientas matemáticas**: Incluye muchas funciones matemáticas (álgebra lineal, transformadas de Fourier, estadísticas, etc.).
- **Base para otras librerías**: Librerías importantes en Inteligencia Artificial y Data Science (como Pandas, TensorFlow, PyTorch y scikit-learn) usan NumPy en su núcleo.
- **Operaciones vectorizadas**: Permite realizar operaciones sobre conjuntos de datos completos sin necesidad de bucles explícitos en Python, lo que facilita y acelera el desarrollo de experimentos y prototipos.

## ¿Qué es un array de NumPy?

Un **array** de NumPy (o `ndarray`) es una estructura de datos que contiene valores de un mismo tipo (generalmente numéricos) y que se organiza en uno o más **dimensiones**. 

Ejemplos:
- Un array unidimensional (similar a una lista)
- Un array bidimensional (matriz)
- Un array de más dimensiones (3D, 4D, etc.)

Esta estructura permite indexación y slicing de manera muy eficiente.

---


In [2]:
import numpy as np

# Versión de NumPy
print("Versión de NumPy:", np.__version__)

Versión de NumPy: 2.2.4


# 1. Creación de Arrays

Existen diferentes maneras de crear arrays en NumPy. Veamos algunas formas básicas:

In [3]:
# Lista de Python a array de NumPy
lista = [1, 2, 3, 4, 5]
array_1d = np.array(lista)
print("Array unidimensional:", array_1d)

# Array bidimensional
matriz = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Array bidimensional:\n", matriz)

# Crear arrays con ceros y unos
array_ceros = np.zeros((2, 3))
array_unos = np.ones((3, 2))
print("Array de ceros:\n", array_ceros)
print("Array de unos:\n", array_unos)

# Crear un array con un rango
array_rango = np.arange(0, 10, 2)
print("Array con rango de 0 a 10 en pasos de 2:", array_rango)

# Array con valores equiespaciados
array_linspace = np.linspace(0, 1, 5)
print("Array con 5 valores entre 0 y 1:", array_linspace)


Array unidimensional: [1 2 3 4 5]
Array bidimensional:
 [[1 2 3]
 [4 5 6]]
Array de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array de unos:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Array con rango de 0 a 10 en pasos de 2: [0 2 4 6 8]
Array con 5 valores entre 0 y 1: [0.   0.25 0.5  0.75 1.  ]


# 2. Indexación y Slicing

Al igual que las listas en Python, los arrays de NumPy permiten acceder a sus elementos mediante **índices**. 
Sin embargo, en arrays multidimensionales, se necesitan varios índices (uno por cada dimensión).

## 2.1 Indexación básica


In [4]:
# Indexación en un array unidimensional
arr = np.array([10, 20, 30, 40, 50])
print("Elementos del array:", arr)
print("Primer elemento:", arr[0])
print("Último elemento:", arr[-1])

# Indexación en un array bidimensional
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


# Fila 0, columna 0
print("Elemento [0, 0]:", arr_2d[0, 0])

# Fila 2, columna 1
print("Elemento [2, 1]:", arr_2d[2, 1])



Elementos del array: [10 20 30 40 50]
Primer elemento: 10
Último elemento: 50
Elemento [0, 0]: 1
Elemento [2, 1]: 8


 ### Fancy Indexing
 
 Fancy indexing (o "indexación avanzada") es una funcionalidad muy potente de NumPy que te permite acceder a elementos de un array utilizando listas o arrays de índices, en lugar de simples enteros o slices (:). Vamos, que puedes seleccionar múltiples elementos no contiguos, en el orden que tú quieras.

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Queremos los elementos en las posiciones 0, 2 y 4
indices = [0, 2, 4]
print(arr[indices])  # [10 30 50]

[10 30 50]


In [6]:
orden = [4, 3, 1, 0]
print(arr[orden])  # [50 40 20 10]


[50 40 20 10]


In [7]:
matriz = np.array([[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]])

# Seleccionamos las filas 0 y 2
print(matriz[[0, 2], :])

#Seleccionamos fila 0 columnas 0 y 2
print(matriz[[0],[0,2]])


[[10 11 12]
 [16 17 18]]
[10 12]


In [8]:
string = 'holahola'


lista = ['hola', 'Alejandro','Carabe']

array = np.array(['hola', 'Alejandro','Carabe'])
array[[0,2]]

array(['hola', 'Carabe'], dtype='<U9')

## 2.2 Slicing (rebanado)
El slicing permite acceder a secciones de un array usando la notación `[start:stop:step]`.

- `start`: Índice de inicio (por defecto, 0).
- `stop`: Índice hasta el cual se hace el slicing (no se incluye en el resultado).
- `step`: Paso entre índices (por defecto, 1).

Veamos algunos ejemplos:


In [9]:
# Slicing en un array unidimensional
arr = np.array([10, 20, 30, 40, 50, 60])
print("Array original:", arr)

# De la posición 1 a la 4 (sin incluir la 4)
print("arr[1:4] =", arr[1:4])

# Desde la posición 2 hasta el final
print("arr[2:] =", arr[2:])

# Desde el inicio hasta la posición 3 (sin incluir la 3)
print("arr[:3] =", arr[:3])

# Con un paso de 2
print("arr[::2] =", arr[::2])

# Slicing en un array 2D
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print("\nArray 2D original:\n", arr_2d)

# Tomar filas 1 y 2, y columnas 0 y 1
print("arr_2d[1:3, 0:2] =\n", arr_2d[1:3, 0:2])

# Tomar todas las filas de la columna 2
print("arr_2d[:, 2] =", arr_2d[:, 2])

# Tomar la primera fila completa
print("arr_2d[0, :] =", arr_2d[0, :])


Array original: [10 20 30 40 50 60]
arr[1:4] = [20 30 40]
arr[2:] = [30 40 50 60]
arr[:3] = [10 20 30]
arr[::2] = [10 30 50]

Array 2D original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr_2d[1:3, 0:2] =
 [[ 5  6]
 [ 9 10]]
arr_2d[:, 2] = [ 3  7 11 15]
arr_2d[0, :] = [1 2 3 4]


# 3. Operaciones Vectorizadas

Una de las grandes ventajas de NumPy es la posibilidad de realizar **operaciones vectorizadas** sobre los arrays, 
lo que significa que podemos aplicar operaciones aritméticas a todos los elementos de un array sin necesidad de usar bucles explícitos. Esto es más rápido y conciso.

Por ejemplo, si queremos sumar, restar, multiplicar o dividir cada elemento de un array por un número, o bien hacer operaciones entre dos arrays de la misma forma:



In [10]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

print("Array x:", x)
print("Array y:", y)
print("Suma de x + 10:", x + 10)
print("Multiplicación de y * 2:", y * 2)
print("Suma de x + y:", x + y)
print("Producto de x * y:", x * y)
print("División y / x:", y / x)


Array x: [1 2 3 4 5]
Array y: [10 20 30 40 50]
Suma de x + 10: [11 12 13 14 15]
Multiplicación de y * 2: [ 20  40  60  80 100]
Suma de x + y: [11 22 33 44 55]
Producto de x * y: [ 10  40  90 160 250]
División y / x: [10. 10. 10. 10. 10.]


## 3.1 Funciones Universales (ufuncs)

NumPy incluye muchas funciones matemáticas (ufuncs) que se aplican elemento a elemento sobre los arrays: `np.sqrt`, `np.exp`, `np.log`, `np.sin`, etc.


In [11]:
import math

valores = np.array([0, math.pi/2, math.pi, 3*math.pi/2, 2*math.pi])
print("Array original (radianes):", valores)
print("Seno:", np.sin(valores))
print("Coseno:", np.cos(valores))
print("Exponencial de x:", np.exp(np.array([1, 2, 3])))
print("Logaritmo natural de x:", np.log(np.array([1, np.e, np.e**2])))


Array original (radianes): [0.         1.57079633 3.14159265 4.71238898 6.28318531]
Seno: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
Coseno: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]
Exponencial de x: [ 2.71828183  7.3890561  20.08553692]
Logaritmo natural de x: [0. 1. 2.]


# 3.2 Ejemplos prácticos de operaciones vectorizadas

Veamos algunos ejemplos reales donde las operaciones vectorizadas nos permiten escribir código más limpio, eficiente y legible.


In [12]:
# Ejemplo 1: Normalización de datos
# 🧠 Aplicación: Preprocesamiento antes de entrenar un modelo (evita que los valores más altos dominen el resultado)

datos = np.array([15, 20, 35, 40, 50])  # Por ejemplo: edades o ingresos
normalizados = (datos - np.min(datos)) / (np.max(datos) - np.min(datos))
print("Datos originales:", datos)
print("Datos normalizados (entre 0 y 1):", normalizados)


Datos originales: [15 20 35 40 50]
Datos normalizados (entre 0 y 1): [0.         0.14285714 0.57142857 0.71428571 1.        ]


In [13]:
# Ejemplo 2: Cálculo de distancia euclidiana entre puntos
# 🧠 Aplicación: En sistemas de recomendación o agrupamiento (clustering), se utiliza para medir la similitud entre usuarios, productos, imágenes, etc.

A = np.array([1, 2, 3])  # Punto A (por ejemplo, características de un usuario)
B = np.array([4, 0, 6])  # Punto B (otro usuario o ítem)
distancia = np.sqrt(np.sum((A - B)**2))
print("Distancia euclidiana entre A y B:", distancia)


Distancia euclidiana entre A y B: 4.69041575982343


In [14]:
# Ejemplo 3: Umbralización (thresholding)
# 🧠 Aplicación: En visión por ordenador o clasificación binaria (por ejemplo, detección de spam), se convierte una probabilidad en una decisión: sí o no.

valores = np.array([0.2, 0.6, 0.8, 0.4])  # Probabilidades de que un correo sea spam
umbral = 0.5
binario = (valores > umbral).astype(int)
print("Probabilidades:", valores)
print("Decisión binaria (umbral = 0.5):", binario)  # 1 = sí (spam), 0 = no


Probabilidades: [0.2 0.6 0.8 0.4]
Decisión binaria (umbral = 0.5): [0 1 1 0]


In [15]:
# Ejemplo 4: ReLU (Rectified Linear Unit)
# 🧠 Aplicación: Es una de las funciones de activación más comunes en redes neuronales. Convierte los valores negativos en 0, acelerando el aprendizaje.

valores = np.array([-3, -1, 0, 2, 4])
relu = np.maximum(0, valores)
print("Valores originales:", valores)
print("Valores tras aplicar ReLU:", relu)


Valores originales: [-3 -1  0  2  4]
Valores tras aplicar ReLU: [0 0 0 2 4]


In [16]:
# Ejemplo 5: Media por columna (axis=0)
# 🧠 Aplicación: Análisis estadístico básico. Por ejemplo, obtener la media de cada variable en una tabla de datos.

matriz = np.array([[1, 2, 3],     # Cada fila puede representar una persona, y cada columna una variable
                   [4, 5, 6],
                   [7, 8, 9]])
media_col = np.mean(matriz, axis=0)
print("Matriz de datos:\n", matriz)
print("Media de cada columna:", media_col)


Matriz de datos:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Media de cada columna: [4. 5. 6.]


## 🔎 Condicionales con `np.where()`

La función `np.where()` nos permite aplicar una condición sobre arrays de forma vectorizada.

📌 Sintaxis:
```python
np.where(condición, valor_si_verdadero, valor_si_falso)


In [18]:
np.where([True, False, True], 'Sí', 'No')  #→ array(['Sí', 'No', 'Sí'], dtype='<U2')


array(['Sí', 'No', 'Sí'], dtype='<U2')

In [19]:
# Otro ejemplo: reemplazar negativos por 0
valores = np.array([-3, 5, -1, 0, 7])
reemplazados = np.where(valores < 0, 0, valores)

print("Original:", valores)
print("Negativos reemplazados por 0:", reemplazados)


Original: [-3  5 -1  0  7]
Negativos reemplazados por 0: [0 5 0 0 7]


## 🧠 Ejercicios con `np.where()`

1. Tienes un array con temperaturas:  
   `temp = np.array([36.5, 37.8, 38.5, 36.9, 39.0])`  
   ➤ Crea un nuevo array que diga `"Fiebre"` si la temperatura es mayor a 37.5, si no `"Normal"`.

2. Dado el array `nums = np.array([10, 15, 20, 25, 30])`  
   ➤ Reemplaza los valores **divisibles por 3** por el valor `"DIV"`, y el resto por `"OK"`.

3. Dado el array `alturas = np.array([1.75, 1.62, 1.90, 1.68, 1.82])`  
   ➤ Crea una clasificación `"Alta"` si la altura es mayor a 1.75, si no `"Media o baja"`.


In [ ]:
temp = np.array([36.5,37.8,38.5,36.9,39.0])
nums = np.array([10,15,20,25,30])
alturas = np.array([1.75,1.62,1.90,1.68,1.82])

print(np.where(temp>37.5,'Fiebre',temp))
print(np.where(nums%3==0,"DIV","OK"))
print(np.where())

['36.5' 'Fiebre' 'Fiebre' '36.9' 'Fiebre']
['OK' 'DIV' 'OK' 'OK' 'DIV']


# 4. Aplicaciones en IA y Data Science

- **Preprocesamiento de datos**: NumPy se emplea para limpiar y transformar datos antes de su uso en modelos de Machine Learning o Deep Learning.
- **Manipulación de tensores**: En redes neuronales, trabajamos con matrices (o tensores) para entrenar modelos. NumPy sirve como base para librerías como TensorFlow o PyTorch.
- **Análisis rápido**: Muchos algoritmos de Data Science se pueden implementar de manera más efectiva y concisa con arrays de NumPy y operaciones vectorizadas.

