# Clase 2: Operaciones matemáticas, estadísticas y manipulación de matrices con NumPy

En esta segunda clase de NumPy, profundizaremos en:
1. **Operaciones matemáticas avanzadas** (suma, diferencia, producto, broadcasting).
2. **Funciones estadísticas** (media, mediana, varianza, percentiles, etc.).
3. **Manipulación de matrices** (reshape, transponer, concatenar, dividir, multiplicación de matrices, etc.).

Empecemos importando la librería e imprimiendo su versión.


In [1]:
import numpy as np

print("Versión de NumPy:", np.__version__)


Versión de NumPy: 1.26.4


## 1. Operaciones matemáticas avanzadas

NumPy ofrece una gran variedad de **ufuncs** (funciones universales), que permiten aplicar operaciones aritméticas de manera vectorizada.

### 1.1 Suma, resta, multiplicación y división
Hagamos un breve repaso y veamos cómo usar `axis` para controlar si sumamos por filas o por columnas en un array 2D.


In [21]:
# Creamos un array 2D
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriz original:\n", matriz)

# Suma total de todos los elementos
print("\nSuma total:", np.sum(matriz))

# Suma por filas (axis=1)
print("Suma por filas:", np.sum(matriz, axis=1))
print("Suma por filas:", np.sum(matriz[[0,2]], axis=1))

# Suma por columnas (axis=0)
print("Suma por columnas:", np.sum(matriz, axis=0))

# Otras operaciones: producto, mínimo, máximo
print("Producto de todos los elementos:", np.prod([matriz[0,2], matriz[0,1]]))
print("Valor mínimo:", np.min(matriz))
print("Valor máximo:", np.max(matriz))


Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma total: 45
Suma por filas: [ 6 15 24]
Suma por filas: [ 6 24]
Suma por columnas: [12 15 18]
Producto de todos los elementos: 6
Valor mínimo: 1
Valor máximo: 9


### 1.2 Broadcasting

El **broadcasting** permite realizar operaciones entre arrays de distintas formas (shapes) siempre que una de ellas sea compatible con la otra. Veamos un ejemplo donde sumamos un vector a cada fila de una matriz.


In [40]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])

print("Matriz A:\n", A)
print("Vector b:", b)

print(A.shape)
print(b.shape)

# Suma con broadcasting
C = A + b
print("\nA + b:\n", C)


Matriz A:
 [[1 2 3]
 [4 5 6]]
Vector b: [10 20 30]
(2, 3)
(3,)

A + b:
 [[11 22 33]
 [14 25 36]]


En este caso, el vector `b` se *expande* para poder sumarse a cada fila de `A`. Este proceso se llama **broadcasting**.

---

## 2. Funciones estadísticas

Ahora veamos algunas funciones comunes para análisis estadístico rápido.

### 2.1 Medidas de tendencia central


In [41]:
datos = np.array([10, 4, 2, 20, 18, 7, 7, 9, 21])

print("Datos:", datos)
print("Media:", np.mean(datos))
print("Mediana:", np.median(datos))
print("Desviación típica:", np.std(datos))
print("Varianza:", np.var(datos))


Datos: [10  4  2 20 18  7  7  9 21]
Media: 10.88888888888889
Mediana: 9.0
Desviación típica: 6.640690132215082
Varianza: 44.098765432098766


### 2.2 Percentiles y cuantiles

Los **percentiles** son valores que dividen el rango de datos; por ejemplo, el percentil 50 (P50) corresponde a la mediana.


In [42]:
# Percentiles
p25 = np.percentile(datos, 25)  # 25% de los valores están por debajo
p50 = np.percentile(datos, 50)  # mediana
p75 = np.percentile(datos, 75)

print("Percentil 25:", p25)
print("Percentil 50 (mediana):", p50)
print("Percentil 75:", p75)


Percentil 25: 7.0
Percentil 50 (mediana): 9.0
Percentil 75: 18.0


Estas medidas son muy útiles para el **análisis exploratorio** de datos (EDA) y para detectar valores atípicos (outliers).

---

## 3. Manipulación de matrices

En NumPy, las operaciones con matrices son cruciales, especialmente en IA y Data Science (para representar datos, pesos de modelos, etc.).

### 3.1 Reshape y Flatten

- `reshape` permite cambiar la forma (shape) de un array sin cambiar sus datos.
- `ravel` o `flatten` "aplanan" un array n-dimensional en uno 1D.


In [ ]:
arr = np.arange(1, 13)  # array desde 1 hasta 12
print("Array 1D:", arr)

# Cambiamos la forma a 3x4 (3 filas, 4 columnas)
arr_reshaped = arr.reshape((3, 4))
print("\nArray reshape a 3x4:\n", arr_reshaped)

# Aplanar de nuevo
arr_flat = arr_reshaped.ravel()  # o arr_reshaped.flatten()
print("\nArray aplanado de nuevo:", arr_flat)
# arr_reshaped.reshape(12,)


Array 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Array reshape a 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array aplanado de nuevo: [ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 3.2 Transposición (transpose)

Si tenemos una matriz, podemos obtener su traspuesta fácilmente con `arr.T`.


In [45]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Matriz original:\n", mat)

mat_T = mat.T
print("\nMatriz traspuesta:\n", mat_T)


Matriz original:
 [[1 2 3]
 [4 5 6]]

Matriz traspuesta:
 [[1 4]
 [2 5]
 [3 6]]


### 3.3 Concatenación y división de arrays

Podemos **concatenar** arrays por filas o columnas (funciones `np.concatenate`, `np.vstack`, `np.hstack`) o **dividir** un array en subarrays (`np.split`, `np.hsplit`, `np.vsplit`).


In [46]:
# Concatenación vertical
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

# Unimos verticalmente (filas)
arr_vertical = np.vstack((arr1, arr2))
print("Concatenación vertical:\n", arr_vertical)

# Unimos horizontalmente (columnas)
arr_horizontal = np.hstack((arr1, arr2))
print("\nConcatenación horizontal:\n", arr_horizontal)

# División de arrays
arr_dividido = np.split(arr_vertical, 2)  # dividimos en 2 subarrays a lo largo del eje 0
print("\nArray dividido en 2:\n", arr_dividido)


Concatenación vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenación horizontal:
 [[1 2 5 6]
 [3 4 7 8]]

Array dividido en 2:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


### 3.4 Operaciones de álgebra lineal (multiplicación de matrices)

En NumPy existen múltiples formas de hacer multiplicación de matrices:
- `*` multiplica elemento a elemento (Hadamard).
- `np.dot(A, B)` o `A.dot(B)` realizan multiplicación de matrices según la definición de álgebra lineal.
- `@` (operador arroba) es equivalente a `np.dot` para arrays 2D.

Veámoslo:


In [49]:
M1 = np.array([[1, 2],
               [3, 4]])
M2 = np.array([[5, 6],
               [7, 8]])

# Multiplicación elemento a elemento
multi_elem = M1 * M2
print("Multiplicación elemento a elemento:\n", multi_elem)

# Producto matricial (álgebra lineal)
multi_dot = np.dot(M1, M2)
print("\nMultiplicación de matrices (dot):\n", multi_dot)

# Operador @
multi_at = M1 @ M2
print("\nMultiplicación de matrices (@):\n", multi_at)

# Comprobar que son iguales
print("\n¿multi_dot == multi_at?", np.array_equal(multi_dot, multi_at))


Multiplicación elemento a elemento:
 [[ 5 12]
 [21 32]]

Multiplicación de matrices (dot):
 [[19 22]
 [43 50]]

Multiplicación de matrices (@):
 [[19 22]
 [43 50]]

¿multi_dot == multi_at? True


* 1 x 5 + 2 x 7 = 19 
* 1 x 6 + 2 x 8 = 22 
* 3 x 5 + 4 x 7 = 43 
* 2 x 7 + 4 x 8 = 50


Para operaciones más avanzadas de **álgebra lineal** (inversas, descomposiciones, determinantes, etc.) existe el submódulo [`np.linalg`](https://numpy.org/doc/stable/reference/routines.linalg.html).

---

## Conclusión

En esta clase, hemos cubierto:
- **Operaciones matemáticas avanzadas** (sumas, productos, broadcasting, etc.).
- **Funciones estadísticas** (media, mediana, varianza, percentiles...).
- **Manipulación de matrices** (reshape, transpose, concat, split, multiplicaciones).

Con esto completamos una base sólida para manejar datos, transformarlos y realizar cálculos tanto en ámbitos científicos como en proyectos de Inteligencia Artificial y Ciencia de Datos.
